packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  appium@2.19.0: true
  better-sqlite3@12.11.1: true
  edgedriver@6.3.0: true
  'esbuild@0.21.5 || 0.28.2': true
  geckodriver@6.1.1: true
  msgpackr-extract@3.0.4: true
  nx@20.8.4: true
  sharp@0.34.2: true
minimumReleaseAgeExclude:
  - '@evolu/common@8.5.0'
  - '@evolu/web@3.1.0'
