import { CurrencyCode, type CurrencyCode as CurrencyCodeType } from './types';

export interface Territory {
    readonly flag: string;
    readonly name: string;
}

type CurrencyToTerritoryMap = Readonly<Record<CurrencyCodeType, ReadonlyArray<Territory>>>;

export const asCurrencyCodeUnsafe = (code: string): CurrencyCodeType => CurrencyCode.orThrow(code);

/**
 * Map of ISO 4217 currency codes to the territories where they are used.
 *
 * Data sources:
 *   - https://en.wikipedia.org/wiki/ISO_4217#Active_codes
 *   - https://en.wikipedia.org/wiki/List_of_circulating_currencies
 */
export const CURRENCY_TERRITORIES = {
    [asCurrencyCodeUnsafe('AED')]: [{ flag: '🇦🇪', name: 'United Arab Emirates' }],
    [asCurrencyCodeUnsafe('AFN')]: [{ flag: '🇦🇫', name: 'Afghanistan' }],
    [asCurrencyCodeUnsafe('ALL')]: [{ flag: '🇦🇱', name: 'Albania' }],
    [asCurrencyCodeUnsafe('AMD')]: [{ flag: '🇦🇲', name: 'Armenia' }],
    [asCurrencyCodeUnsafe('ANG')]: [
        { flag: '🇨🇼', name: 'Curaçao' },
        { flag: '🇸🇽', name: 'Sint Maarten' },
    ],
    [asCurrencyCodeUnsafe('AOA')]: [{ flag: '🇦🇴', name: 'Angola' }],
    [asCurrencyCodeUnsafe('ARS')]: [{ flag: '🇦🇷', name: 'Argentina' }],
    [asCurrencyCodeUnsafe('AUD')]: [
        { flag: '🇦🇺', name: 'Australia' },
        { flag: '🇨🇽', name: 'Christmas Island' },
        { flag: '🇨🇨', name: 'Cocos (Keeling) Islands' },
        { flag: '🇰🇮', name: 'Kiribati' },
        { flag: '🇳🇷', name: 'Nauru' },
        { flag: '🇳🇫', name: 'Norfolk Island' },
        { flag: '🇹🇻', name: 'Tuvalu' },
    ],
    [asCurrencyCodeUnsafe('AWG')]: [{ flag: '🇦🇼', name: 'Aruba' }],
    [asCurrencyCodeUnsafe('AZN')]: [{ flag: '🇦🇿', name: 'Azerbaijan' }],
    [asCurrencyCodeUnsafe('BAM')]: [{ flag: '🇧🇦', name: 'Bosnia and Herzegovina' }],
    [asCurrencyCodeUnsafe('BBD')]: [{ flag: '🇧🇧', name: 'Barbados' }],
    [asCurrencyCodeUnsafe('BDT')]: [{ flag: '🇧🇩', name: 'Bangladesh' }],
    [asCurrencyCodeUnsafe('BHD')]: [{ flag: '🇧🇭', name: 'Bahrain' }],
    [asCurrencyCodeUnsafe('BIF')]: [{ flag: '🇧🇮', name: 'Burundi' }],
    [asCurrencyCodeUnsafe('BMD')]: [{ flag: '🇧🇲', name: 'Bermuda' }],
    [asCurrencyCodeUnsafe('BND')]: [
        { flag: '🇧🇳', name: 'Brunei' },
        { flag: '🇸🇬', name: 'Singapore' },
    ],
    [asCurrencyCodeUnsafe('BOB')]: [{ flag: '🇧🇴', name: 'Bolivia' }],
    [asCurrencyCodeUnsafe('BRL')]: [{ flag: '🇧🇷', name: 'Brazil' }],
    [asCurrencyCodeUnsafe('BSD')]: [{ flag: '🇧🇸', name: 'Bahamas' }],
    [asCurrencyCodeUnsafe('BTN')]: [{ flag: '🇧🇹', name: 'Bhutan' }],
    [asCurrencyCodeUnsafe('BWP')]: [{ flag: '🇧🇼', name: 'Botswana' }],
    [asCurrencyCodeUnsafe('BYN')]: [{ flag: '🇧🇾', name: 'Belarus' }],
    [asCurrencyCodeUnsafe('BZD')]: [{ flag: '🇧🇿', name: 'Belize' }],
    [asCurrencyCodeUnsafe('CAD')]: [{ flag: '🇨🇦', name: 'Canada' }],
    [asCurrencyCodeUnsafe('CDF')]: [{ flag: '🇨🇩', name: 'Democratic Republic of the Congo' }],
    [asCurrencyCodeUnsafe('CHF')]: [
        { flag: '🇨🇭', name: 'Switzerland' },
        { flag: '🇱🇮', name: 'Liechtenstein' },
    ],
    [asCurrencyCodeUnsafe('CLP')]: [{ flag: '🇨🇱', name: 'Chile' }],
    [asCurrencyCodeUnsafe('CNY')]: [{ flag: '🇨🇳', name: 'China' }],
    [asCurrencyCodeUnsafe('COP')]: [{ flag: '🇨🇴', name: 'Colombia' }],
    [asCurrencyCodeUnsafe('CRC')]: [{ flag: '🇨🇷', name: 'Costa Rica' }],
    [asCurrencyCodeUnsafe('CUP')]: [{ flag: '🇨🇺', name: 'Cuba' }],
    [asCurrencyCodeUnsafe('CVE')]: [{ flag: '🇨🇻', name: 'Cabo Verde' }],
    [asCurrencyCodeUnsafe('CZK')]: [{ flag: '🇨🇿', name: 'Czechia' }],
    [asCurrencyCodeUnsafe('DJF')]: [{ flag: '🇩🇯', name: 'Djibouti' }],
    [asCurrencyCodeUnsafe('DKK')]: [
        { flag: '🇩🇰', name: 'Denmark' },
        { flag: '🇫🇴', name: 'Faroe Islands' },
        { flag: '🇬🇱', name: 'Greenland' },
    ],
    [asCurrencyCodeUnsafe('DOP')]: [{ flag: '🇩🇴', name: 'Dominican Republic' }],
    [asCurrencyCodeUnsafe('DZD')]: [{ flag: '🇩🇿', name: 'Algeria' }],
    [asCurrencyCodeUnsafe('EGP')]: [{ flag: '🇪🇬', name: 'Egypt' }],
    [asCurrencyCodeUnsafe('ERN')]: [{ flag: '🇪🇷', name: 'Eritrea' }],
    [asCurrencyCodeUnsafe('ETB')]: [{ flag: '🇪🇹', name: 'Ethiopia' }],
    [asCurrencyCodeUnsafe('EUR')]: [
        { flag: '🇪🇺', name: 'EU' },
        { flag: '🇦🇽', name: 'Åland Islands' },
        { flag: '🇦🇩', name: 'Andorra' },
        { flag: '🇦🇹', name: 'Austria' },
        { flag: '🇧🇪', name: 'Belgium' },
        { flag: '🇧🇬', name: 'Bulgaria' },
        { flag: '🇨🇾', name: 'Cyprus' },
        { flag: '🇭🇷', name: 'Croatia' },
        { flag: '🇪🇪', name: 'Estonia' },
        { flag: '🇫🇮', name: 'Finland' },
        { flag: '🇫🇷', name: 'France' },
        { flag: '🇩🇪', name: 'Germany' },
        { flag: '🇬🇷', name: 'Greece' },
        { flag: '🇬🇵', name: 'Guadeloupe' },
        { flag: '🇮🇪', name: 'Ireland' },
        { flag: '🇮🇹', name: 'Italy' },
        { flag: '🇽🇰', name: 'Kosovo' },
        { flag: '🇱🇻', name: 'Latvia' },
        { flag: '🇱🇹', name: 'Lithuania' },
        { flag: '🇱🇺', name: 'Luxembourg' },
        { flag: '🇲🇹', name: 'Malta' },
        { flag: '🇬🇫', name: 'French Guiana' },
        { flag: '🇲🇶', name: 'Martinique' },
        { flag: '🇾🇹', name: 'Mayotte' },
        { flag: '🇲🇨', name: 'Monaco' },
        { flag: '🇲🇪', name: 'Montenegro' },
        { flag: '🇳🇱', name: 'Netherlands' },
        { flag: '🇵🇹', name: 'Portugal' },
        { flag: '🇷🇪', name: 'Réunion' },
        { flag: '🇧🇱', name: 'Saint Barthélemy' },
        { flag: '🇲🇫', name: 'Saint Martin' },
        { flag: '🇵🇲', name: 'Saint Pierre and Miquelon' },
        { flag: '🇸🇲', name: 'San Marino' },
        { flag: '🇸🇰', name: 'Slovakia' },
        { flag: '🇸🇮', name: 'Slovenia' },
        { flag: '🇪🇸', name: 'Spain' },
        { flag: '🇻🇦', name: 'Vatican City' },
    ],
    [asCurrencyCodeUnsafe('FJD')]: [{ flag: '🇫🇯', name: 'Fiji' }],
    [asCurrencyCodeUnsafe('FKP')]: [{ flag: '🇫🇰', name: 'Falkland Islands' }],
    [asCurrencyCodeUnsafe('GBP')]: [
        { flag: '🇬🇧', name: 'United Kingdom' },
        { flag: '🇮🇲', name: 'Isle of Man' },
        { flag: '🇯🇪', name: 'Jersey' },
        { flag: '🇬🇬', name: 'Guernsey' },
        { flag: '🇹🇦', name: 'Tristan da Cunha' },
    ],
    [asCurrencyCodeUnsafe('GEL')]: [{ flag: '🇬🇪', name: 'Georgia' }],
    [asCurrencyCodeUnsafe('GHS')]: [{ flag: '🇬🇭', name: 'Ghana' }],
    [asCurrencyCodeUnsafe('GIP')]: [{ flag: '🇬🇮', name: 'Gibraltar' }],
    [asCurrencyCodeUnsafe('GMD')]: [{ flag: '🇬🇲', name: 'Gambia' }],
    [asCurrencyCodeUnsafe('GNF')]: [{ flag: '🇬🇳', name: 'Guinea' }],
    [asCurrencyCodeUnsafe('GTQ')]: [{ flag: '🇬🇹', name: 'Guatemala' }],
    [asCurrencyCodeUnsafe('GYD')]: [{ flag: '🇬🇾', name: 'Guyana' }],
    [asCurrencyCodeUnsafe('HKD')]: [{ flag: '🇭🇰', name: 'Hong Kong' }],
    [asCurrencyCodeUnsafe('HNL')]: [{ flag: '🇭🇳', name: 'Honduras' }],
    [asCurrencyCodeUnsafe('HTG')]: [{ flag: '🇭🇹', name: 'Haiti' }],
    [asCurrencyCodeUnsafe('HUF')]: [{ flag: '🇭🇺', name: 'Hungary' }],
    [asCurrencyCodeUnsafe('IDR')]: [{ flag: '🇮🇩', name: 'Indonesia' }],
    [asCurrencyCodeUnsafe('ILS')]: [{ flag: '🇮🇱', name: 'Israel' }],
    [asCurrencyCodeUnsafe('INR')]: [
        { flag: '🇮🇳', name: 'India' },
        { flag: '🇧🇹', name: 'Bhutan' },
    ],
    [asCurrencyCodeUnsafe('IQD')]: [{ flag: '🇮🇶', name: 'Iraq' }],
    [asCurrencyCodeUnsafe('IRR')]: [{ flag: '🇮🇷', name: 'Iran' }],
    [asCurrencyCodeUnsafe('ISK')]: [{ flag: '🇮🇸', name: 'Iceland' }],
    [asCurrencyCodeUnsafe('JMD')]: [{ flag: '🇯🇲', name: 'Jamaica' }],
    [asCurrencyCodeUnsafe('JOD')]: [{ flag: '🇯🇴', name: 'Jordan' }],
    [asCurrencyCodeUnsafe('JPY')]: [{ flag: '🇯🇵', name: 'Japan' }],
    [asCurrencyCodeUnsafe('KES')]: [{ flag: '🇰🇪', name: 'Kenya' }],
    [asCurrencyCodeUnsafe('KGS')]: [{ flag: '🇰🇬', name: 'Kyrgyzstan' }],
    [asCurrencyCodeUnsafe('KHR')]: [{ flag: '🇰🇭', name: 'Cambodia' }],
    [asCurrencyCodeUnsafe('KMF')]: [{ flag: '🇰🇲', name: 'Comoros' }],
    [asCurrencyCodeUnsafe('KPW')]: [{ flag: '🇰🇵', name: 'North Korea' }],
    [asCurrencyCodeUnsafe('KRW')]: [{ flag: '🇰🇷', name: 'South Korea' }],
    [asCurrencyCodeUnsafe('KWD')]: [{ flag: '🇰🇼', name: 'Kuwait' }],
    [asCurrencyCodeUnsafe('KYD')]: [{ flag: '🇰🇾', name: 'Cayman Islands' }],
    [asCurrencyCodeUnsafe('KZT')]: [{ flag: '🇰🇿', name: 'Kazakhstan' }],
    [asCurrencyCodeUnsafe('LAK')]: [{ flag: '🇱🇦', name: 'Laos' }],
    [asCurrencyCodeUnsafe('LBP')]: [{ flag: '🇱🇧', name: 'Lebanon' }],
    [asCurrencyCodeUnsafe('LKR')]: [{ flag: '🇱🇰', name: 'Sri Lanka' }],
    [asCurrencyCodeUnsafe('LRD')]: [{ flag: '🇱🇷', name: 'Liberia' }],
    [asCurrencyCodeUnsafe('LSL')]: [{ flag: '🇱🇸', name: 'Lesotho' }],
    [asCurrencyCodeUnsafe('LYD')]: [{ flag: '🇱🇾', name: 'Libya' }],
    [asCurrencyCodeUnsafe('MAD')]: [
        { flag: '🇲🇦', name: 'Morocco' },
        { flag: '🇪🇭', name: 'Western Sahara' },
    ],
    [asCurrencyCodeUnsafe('MDL')]: [{ flag: '🇲🇩', name: 'Moldova' }],
    [asCurrencyCodeUnsafe('MGA')]: [{ flag: '🇲🇬', name: 'Madagascar' }],
    [asCurrencyCodeUnsafe('MKD')]: [{ flag: '🇲🇰', name: 'North Macedonia' }],
    [asCurrencyCodeUnsafe('MMK')]: [{ flag: '🇲🇲', name: 'Myanmar' }],
    [asCurrencyCodeUnsafe('MNT')]: [{ flag: '🇲🇳', name: 'Mongolia' }],
    [asCurrencyCodeUnsafe('MOP')]: [{ flag: '🇲🇴', name: 'Macau' }],
    [asCurrencyCodeUnsafe('MRU')]: [{ flag: '🇲🇷', name: 'Mauritania' }],
    [asCurrencyCodeUnsafe('MUR')]: [{ flag: '🇲🇺', name: 'Mauritius' }],
    [asCurrencyCodeUnsafe('MVR')]: [{ flag: '🇲🇻', name: 'Maldives' }],
    [asCurrencyCodeUnsafe('MWK')]: [{ flag: '🇲🇼', name: 'Malawi' }],
    [asCurrencyCodeUnsafe('MXN')]: [{ flag: '🇲🇽', name: 'Mexico' }],
    [asCurrencyCodeUnsafe('MYR')]: [{ flag: '🇲🇾', name: 'Malaysia' }],
    [asCurrencyCodeUnsafe('MZN')]: [{ flag: '🇲🇿', name: 'Mozambique' }],
    [asCurrencyCodeUnsafe('NAD')]: [{ flag: '🇳🇦', name: 'Namibia' }],
    [asCurrencyCodeUnsafe('NGN')]: [{ flag: '🇳🇬', name: 'Nigeria' }],
    [asCurrencyCodeUnsafe('NIO')]: [{ flag: '🇳🇮', name: 'Nicaragua' }],
    [asCurrencyCodeUnsafe('NOK')]: [
        { flag: '🇳🇴', name: 'Norway' },
        { flag: '🇸🇯', name: 'Svalbard and Jan Mayen' },
    ],
    [asCurrencyCodeUnsafe('NPR')]: [{ flag: '🇳🇵', name: 'Nepal' }],
    [asCurrencyCodeUnsafe('NZD')]: [
        { flag: '🇳🇿', name: 'New Zealand' },
        { flag: '🇨🇰', name: 'Cook Islands' },
        { flag: '🇳🇺', name: 'Niue' },
        { flag: '🇵🇳', name: 'Pitcairn Islands' },
        { flag: '🇹🇰', name: 'Tokelau' },
    ],
    [asCurrencyCodeUnsafe('OMR')]: [{ flag: '🇴🇲', name: 'Oman' }],
    [asCurrencyCodeUnsafe('PAB')]: [{ flag: '🇵🇦', name: 'Panama' }],
    [asCurrencyCodeUnsafe('PEN')]: [{ flag: '🇵🇪', name: 'Peru' }],
    [asCurrencyCodeUnsafe('PGK')]: [{ flag: '🇵🇬', name: 'Papua New Guinea' }],
    [asCurrencyCodeUnsafe('PHP')]: [{ flag: '🇵🇭', name: 'Philippines' }],
    [asCurrencyCodeUnsafe('PKR')]: [{ flag: '🇵🇰', name: 'Pakistan' }],
    [asCurrencyCodeUnsafe('PLN')]: [{ flag: '🇵🇱', name: 'Poland' }],
    [asCurrencyCodeUnsafe('PYG')]: [{ flag: '🇵🇾', name: 'Paraguay' }],
    [asCurrencyCodeUnsafe('QAR')]: [{ flag: '🇶🇦', name: 'Qatar' }],
    [asCurrencyCodeUnsafe('RON')]: [{ flag: '🇷🇴', name: 'Romania' }],
    [asCurrencyCodeUnsafe('RSD')]: [{ flag: '🇷🇸', name: 'Serbia' }],
    [asCurrencyCodeUnsafe('RUB')]: [{ flag: '🇷🇺', name: 'Russia' }],
    [asCurrencyCodeUnsafe('RWF')]: [{ flag: '🇷🇼', name: 'Rwanda' }],
    [asCurrencyCodeUnsafe('SAR')]: [{ flag: '🇸🇦', name: 'Saudi Arabia' }],
    [asCurrencyCodeUnsafe('SBD')]: [{ flag: '🇸🇧', name: 'Solomon Islands' }],
    [asCurrencyCodeUnsafe('SCR')]: [{ flag: '🇸🇨', name: 'Seychelles' }],
    [asCurrencyCodeUnsafe('SDG')]: [{ flag: '🇸🇩', name: 'Sudan' }],
    [asCurrencyCodeUnsafe('SEK')]: [{ flag: '🇸🇪', name: 'Sweden' }],
    [asCurrencyCodeUnsafe('SGD')]: [
        { flag: '🇧🇳', name: 'Brunei' },
        { flag: '🇸🇬', name: 'Singapore' },
    ],
    [asCurrencyCodeUnsafe('SHP')]: [
        { flag: '🇸🇭', name: 'Saint Helena' },
        { flag: '🇦🇨', name: 'Ascension Island' },
    ],
    [asCurrencyCodeUnsafe('SLE')]: [{ flag: '🇸🇱', name: 'Sierra Leone' }],
    [asCurrencyCodeUnsafe('SOS')]: [{ flag: '🇸🇴', name: 'Somalia' }],
    [asCurrencyCodeUnsafe('SRD')]: [{ flag: '🇸🇷', name: 'Suriname' }],
    [asCurrencyCodeUnsafe('SSP')]: [{ flag: '🇸🇸', name: 'South Sudan' }],
    [asCurrencyCodeUnsafe('STN')]: [{ flag: '🇸🇹', name: 'São Tomé and Príncipe' }],
    [asCurrencyCodeUnsafe('SVC')]: [{ flag: '🇸🇻', name: 'El Salvador' }],
    [asCurrencyCodeUnsafe('SYP')]: [{ flag: '🇸🇾', name: 'Syria' }],
    [asCurrencyCodeUnsafe('SZL')]: [{ flag: '🇸🇿', name: 'Eswatini' }],
    [asCurrencyCodeUnsafe('THB')]: [{ flag: '🇹🇭', name: 'Thailand' }],
    [asCurrencyCodeUnsafe('TJS')]: [{ flag: '🇹🇯', name: 'Tajikistan' }],
    [asCurrencyCodeUnsafe('TMT')]: [{ flag: '🇹🇲', name: 'Turkmenistan' }],
    [asCurrencyCodeUnsafe('TND')]: [{ flag: '🇹🇳', name: 'Tunisia' }],
    [asCurrencyCodeUnsafe('TOP')]: [{ flag: '🇹🇴', name: 'Tonga' }],
    [asCurrencyCodeUnsafe('TRY')]: [
        { flag: '🇹🇷', name: 'Turkey' },
        { flag: '🇹🇷', name: 'Northern Cyprus' },
    ],
    [asCurrencyCodeUnsafe('TTD')]: [{ flag: '🇹🇹', name: 'Trinidad and Tobago' }],
    [asCurrencyCodeUnsafe('TWD')]: [{ flag: '🇹�', name: 'Taiwan' }],
    [asCurrencyCodeUnsafe('TZS')]: [{ flag: '🇹🇿', name: 'Tanzania' }],
    [asCurrencyCodeUnsafe('UAH')]: [{ flag: '🇺🇦', name: 'Ukraine' }],
    [asCurrencyCodeUnsafe('UGX')]: [{ flag: '🇺🇬', name: 'Uganda' }],
    [asCurrencyCodeUnsafe('USD')]: [
        { flag: '🇺🇸', name: 'United States' },
        { flag: '🇦🇸', name: 'American Samoa' },
        { flag: '🇮🇴', name: 'British Indian Ocean Territory' },
        { flag: '🇻🇬', name: 'British Virgin Islands' },
        { flag: '🇧🇶', name: 'Caribbean Netherlands' },
        { flag: '🇪🇨', name: 'Ecuador' },
        { flag: '🇸🇻', name: 'El Salvador' },
        { flag: '🇬🇺', name: 'Guam' },
        { flag: '🇲🇭', name: 'Marshall Islands' },
        { flag: '🇫🇲', name: 'Federated States of Micronesia' },
        { flag: '🇲🇵', name: 'Northern Mariana Islands' },
        { flag: '🇵🇼', name: 'Palau' },
        { flag: '🇵🇦', name: 'Panama' },
        { flag: '🇵🇷', name: 'Puerto Rico' },
        { flag: '🇹🇱', name: 'Timor-Leste' },
        { flag: '🇹🇨', name: 'Turks and Caicos Islands' },
        { flag: '🇻🇮', name: 'U.S. Virgin Islands' },
    ],
    [asCurrencyCodeUnsafe('UYU')]: [{ flag: '🇺🇾', name: 'Uruguay' }],
    [asCurrencyCodeUnsafe('UZS')]: [{ flag: '🇺🇿', name: 'Uzbekistan' }],
    [asCurrencyCodeUnsafe('VES')]: [{ flag: '🇻🇪', name: 'Venezuela' }],
    [asCurrencyCodeUnsafe('VND')]: [{ flag: '🇻🇳', name: 'Vietnam' }],
    [asCurrencyCodeUnsafe('VUV')]: [{ flag: '🇻🇺', name: 'Vanuatu' }],
    [asCurrencyCodeUnsafe('WST')]: [{ flag: '🇼🇸', name: 'Samoa' }],
    [asCurrencyCodeUnsafe('XAF')]: [
        { flag: '🇨🇲', name: 'Cameroon' },
        { flag: '🇨🇫', name: 'Central African Republic' },
        { flag: '🇨🇬', name: 'Republic of the Congo' },
        { flag: '🇹🇩', name: 'Chad' },
        { flag: '🇬🇶', name: 'Equatorial Guinea' },
        { flag: '🇬🇦', name: 'Gabon' },
    ],
    [asCurrencyCodeUnsafe('XCD')]: [
        { flag: '🇦🇮', name: 'Anguilla' },
        { flag: '🇦🇬', name: 'Antigua and Barbuda' },
        { flag: '🇩🇲', name: 'Dominica' },
        { flag: '🇬🇩', name: 'Grenada' },
        { flag: '🇲🇸', name: 'Montserrat' },
        { flag: '🇰🇳', name: 'Saint Kitts and Nevis' },
        { flag: '🇱🇨', name: 'Saint Lucia' },
        { flag: '🇻🇨', name: 'Saint Vincent and the Grenadines' },
    ],
    [asCurrencyCodeUnsafe('XOF')]: [
        { flag: '🇧🇯', name: 'Benin' },
        { flag: '🇧🇫', name: 'Burkina Faso' },
        { flag: '🇨🇮', name: "Côte d'Ivoire" },
        { flag: '🇬🇼', name: 'Guinea-Bissau' },
        { flag: '🇲🇱', name: 'Mali' },
        { flag: '🇳🇪', name: 'Niger' },
        { flag: '🇸🇳', name: 'Senegal' },
        { flag: '🇹🇬', name: 'Togo' },
    ],
    [asCurrencyCodeUnsafe('XPF')]: [
        { flag: '🇵🇫', name: 'French Polynesia' },
        { flag: '🇳🇨', name: 'New Caledonia' },
        { flag: '🇼🇫', name: 'Wallis and Futuna' },
    ],
    [asCurrencyCodeUnsafe('YER')]: [{ flag: '🇾🇪', name: 'Yemen' }],
    [asCurrencyCodeUnsafe('ZAR')]: [
        { flag: '🇸🇿', name: 'Eswatini' },
        { flag: '🇱🇸', name: 'Lesotho' },
        { flag: '🇳🇦', name: 'Namibia' },
        { flag: '🇿🇦', name: 'South Africa' },
    ],
    [asCurrencyCodeUnsafe('ZMW')]: [{ flag: '🇿🇲', name: 'Zambia' }],
} satisfies CurrencyToTerritoryMap;

export const getFlagsForCurrency = (currencyCode: CurrencyCodeType): ReadonlyArray<string> => [
    ...new Set((CURRENCY_TERRITORIES[currencyCode] ?? []).map(t => t.flag)),
];

export const getTerritoryNamesForCurrency = (
    currencyCode: CurrencyCodeType,
): ReadonlyArray<string> => (CURRENCY_TERRITORIES[currencyCode] ?? []).map(t => t.name);

export const isFiatCurrency = (currencyCode: CurrencyCodeType): boolean =>
    Object.hasOwn(CURRENCY_TERRITORIES, currencyCode);

export const currencyMatchesTerritory = (
    currencyCode: CurrencyCodeType,
    searchTerm: string,
): boolean => {
    const term = searchTerm.toLowerCase();

    return (CURRENCY_TERRITORIES[currencyCode] ?? []).some(t =>
        t.name.toLowerCase().includes(term),
    );
};
